[package]
name = "lune-std-stdio"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"
repository = "https://github.com/lune-org/lune"
description = "Lune standard library - Stdio"

[lib]
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
dialoguer = "0.11"
mlua = { version = "0.9.7", features = ["luau"] }
mlua-luau-scheduler = "0.0.2"

tokio = { version = "1", default-features = false, features = [
    "io-std",
    "io-util",
] }

lune-utils = { version = "0.1.0", path = "../lune-utils" }
