[package]
name = "lune-cli"
publish = false
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[[bin]]
name = "lune"
path = "src/main.rs"

[features]
default = []
roblox = ["lune/roblox"]

[dependencies]

lune = { path = "../lib" }

console.workspace = true
directories.workspace = true
futures-util.workspace = true
once_cell.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
tokio.workspace = true

anyhow = "1.0"
env_logger = "0.10"
itertools = "0.10"

clap = { version = "4.1", features = ["derive"] }
full_moon = { version = "0.17", features = ["roblox"] }
include_dir = { version = "0.7.3", features = ["glob"] }
regex = { version = "1.7", default-features = false, features = [
	"std",
	"unicode-perl",
] }
