[package]
name = "lune-roblox"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[lib]
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
mlua = { version = "0.9.7", features = ["luau"] }

glam = "0.27"
rand = "0.8"
thiserror = "1.0"
once_cell = "1.17"

rbx_cookie = { version = "0.1.4", default-features = false }

rbx_binary = "0.7.3"
rbx_dom_weak = "2.6.0"
rbx_reflection = "4.4.0"
rbx_reflection_database = "0.2.9"
rbx_xml = "0.13.2"

lune-utils = { version = "0.1.0", path = "../lune-utils" }
